modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL"

[[mods]]
modId="tinkervillager"
version="1.0.0"
displayName="Tinker Villager"
authors="Kakyoin17"
description='''Tinker Villagers.'''

[[dependencies.tinkervillager]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.tinkervillager]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
